spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.199.165:3306/gulimall_sms
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 500000
      maximum-pool-size: 20
  application:
    name: gulimall-coupon
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.199.165 #nacos注册中心地址
    sentinel:
      transport:
        dashboard: 192.168.199.165:8080
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  #采样取值介于 0到1之间，1则表示全部收集
  sleuth:
    sampler:
      probability: 1

  #动态刷新配置 ---需要忽略权限拦截
  management:
    endpoints:
      web:
        exposure:
          include: refresh

#  # jackson时间格式化
  jackson:
    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm:ss
#  mvc:
#    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS Z

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 7000

logging:
  level:
    io.niceseason.gulimall.coupon.dao: debug


management:
  endpoints:
    web:
      exposure:
        include: '*'
